=== Subash324/Web-Technology/labProject/XML/xsd_5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="class">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="student" maxOccurs="unbounded" >
                <xs:complexType  mixed="true">
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="id" type="xs:integer"/>
                        <xs:element name="branch" type="xs:string" minOccurs="1" maxOccurs="3"/>
                        <xs:element name="cgpa" type="xs:string"/>
            
                    </xs:sequence>
        <!-- <xs:attribute name="id" type="xs:integer" use="required"/> -->

                </xs:complexType>
            </xs:element>
          

        </xs:sequence>
        
    </xs:complexType>
    
</xs:element>

</xs:schema>

=== Subash324/Web-Technology/labProject/XML/Ajax_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_5.xsd">
     <student  >
        <name> Subhash </name>
        <id> 001 </id>
        <branch> CSIT </branch>
        <cgpa> 9.0 </cgpa>
        </student>
        <student >
        <name> Mahesh </name>
        <id> 003 </id>
        <branch> BCA </branch>
        <cgpa> 8.0 </cgpa>
        </student>
        <student >
        <name> Anup </name>
        <id> 008 </id>
        <branch> BBM </branch>
        <cgpa> 7.8 </cgpa></student>
       
    
        </class>
